#!/bin/sh

set -eu
IFS=$'\n'

# A hook script to reformat code based on .editorconfig
# Requires at least .NET 5. Called after submitting a commit msg. Can be
# disabled with '--no-verify' flag.

echo "Launching pre-commit hook that runs JetBrains CodeCleanup cli tool"

# skip if there are no csharp files in index (--diff-filter=d means to look at not deleted files only)
staged_files=$(git diff --name-only --staged --diff-filter=d)
unstaged_files=$(git diff --name-only --diff-filter=d)

if ! echo "$staged_files" | grep -Eq '(\.cshtml|\.cs)$'; then
    echo "Skipping code cleanup, because no csharp files were found in index"
    sleep 1
    exit 0
fi

for staged_file in ${staged_files[@]}
do
    if echo $staged_file | grep -Fxq "$unstaged_files"; then
        # After code cleanup we have to re-add staged files, if a file is
        # partially staged we will add the whole file and we don't want that
        echo "Skipping code cleanup, because $staged_file is partially staged"
        sleep 1
        exit 0
    fi
done

dotnet tool restore

# if you want to only reformat code add --profile=$jb_profile
# jb_profile="Built-in: Reformat Code"
include_string=$(echo "$staged_files" | sed ':a;N;$!ba;s/\n/;/g')
dotnet jb cleanupcode *.sln --include="$include_string" --verbosity=INFO
echo "$staged_files" | xargs -t -l git add

echo "Precommit hook finished"
sleep 1
